basePath: /
definitions:
  models.MonthDate:
    properties:
      time:
        type: string
      valid:
        type: boolean
    type: object
  models.Subscription:
    properties:
      end_date:
        $ref: '#/definitions/models.MonthDate'
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        $ref: '#/definitions/models.MonthDate'
      user_id:
        type: string
    type: object
  subs.CreateSubscriptionRequest:
    properties:
      end_date:
        example: 12-2024
        type: string
      price:
        example: 1000
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 01-2024
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  subs.ErrorResponse:
    properties:
      message:
        example: error description
        type: string
    type: object
  subs.SubscriptionResponse:
    properties:
      end_date:
        example: 12-2024
        type: string
      id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
      price:
        example: 1000
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 01-2024
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  subs.SummaryRequest:
    properties:
      end_date:
        example: 12-2024
        type: string
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 01-2024
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  subs.SummaryResponse:
    properties:
      summary:
        example: 12000
        type: integer
    type: object
  subs.UpdateSubscriptionRequest:
    properties:
      end_date:
        example: 12-2024
        type: string
      price:
        example: 1500
        type: integer
      service_name:
        example: Netflix Premium
        type: string
      start_date:
        example: 01-2024
        type: string
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Subscriptions API
  version: "1.0"
paths:
  /subs:
    post:
      consumes:
      - application/json
      parameters:
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/subs.CreateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/subs.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
      summary: Create subscription
      tags:
      - subscriptions
  /subs/{id}:
    get:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subs.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
      summary: Get subscription
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/subs.UpdateSubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subs.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
      summary: Update subscription
      tags:
      - subscriptions
  /subs/list/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Subscription'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List subscriptions
      tags:
      - subscriptions
  /subs/summary:
    post:
      consumes:
      - application/json
      parameters:
      - description: Summary request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/subs.SummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subs.SummaryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/subs.ErrorResponse'
      summary: Calculate total
      tags:
      - subscriptions
swagger: "2.0"
